services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompt_few_shot_app
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure_service
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report

  allure-ui:
    image: frankescobar/allure-docker-service-ui:latest
    container_name: allure_ui
    environment:
      - ALLURE_DOCKER_PUBLIC_API_URL=http://localhost:5050
    ports:
      - "5252:5252"
    depends_on:
      - allure
